### ISSUE TITLE
Run Dev Server: No buildable Go source files

### ISSUE THREAD

**Issue by flumonion** [stock2shop/sync#2]
As per readme:

`go get github.com/stock2shop/sync`

Results in 

`package github.com/stock2shop/sync: no buildable Go source files in /Users/chris/go/src/github.com/stock2shop/sync`

**Comment by mozey** [comment]
That's fine, it's not an error. Maybe I can add and empty go file in the project root so go get doesn't do that. The rest of the instructions should still work?

**Comment by mozey** [comment]
I've added a dummy `sync/main.go` to prevent that message
